# Generated by Django 5.2.4 on 2025-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('points_cost', models.PositiveIntegerField(verbose_name='Стоимость в баллах')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/', verbose_name='Фото')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ['points_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Выдана')], default='pending', max_length=20, verbose_name='Статус')),
                ('points_spent', models.PositiveIntegerField(verbose_name='Потрачено баллов')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Заявка на награду',
                'verbose_name_plural': 'Заявки на награды',
                'ordering': ['-claimed_at'],
            },
        ),
    ]
