# Generated by Django 5.2.4 on 2025-08-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardclaim',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['coach', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Обработал'),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.reward', verbose_name='Награда'),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
    ]
