# Generated by Django 5.2.4 on 2025-08-01 11:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('weight_category', models.CharField(blank=True, max_length=50, verbose_name='Весовая категория')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт в годах')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
            ],
            options={
                'verbose_name': 'Заявка на турнир',
                'verbose_name_plural': 'Заявки на турниры',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('all', 'Все уровни')], default='all', max_length=20, verbose_name='Уровень')),
                ('max_participants', models.PositiveIntegerField(default=50, verbose_name='Максимум участников')),
                ('registration_deadline', models.DateTimeField(verbose_name='Дедлайн регистрации')),
                ('tournament_date', models.DateTimeField(verbose_name='Дата турнира')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Взнос за участие')),
                ('prize_pool', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Призовой фонд')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gym', verbose_name='Академия')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-tournament_date'],
            },
        ),
    ]
