# Generated by Django 5.2.4 on 2025-08-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'role__in': ['coach', 'admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='tournamentapplication',
            name='participant',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AddField(
            model_name='tournamentapplication',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['coach', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_tournament_applications', to=settings.AUTH_USER_MODEL, verbose_name='Обработал'),
        ),
        migrations.AddField(
            model_name='tournamentapplication',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tournaments.tournament', verbose_name='Турнир'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentapplication',
            unique_together={('tournament', 'participant')},
        ),
    ]
