# Generated by Django 5.2.4 on 2025-08-01 11:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тренировки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Максимум участников')),
                ('duration', models.PositiveIntegerField(help_text='Длительность в минутах', verbose_name='Длительность')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
            ],
            options={
                'verbose_name': 'Заявка на тренировку',
                'verbose_name_plural': 'Заявки на тренировки',
                'ordering': ['-applied_at'],
            },
        ),
    ]
