# Generated by Django 5.2.4 on 2025-08-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='training',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gym', verbose_name='Академия'),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Обработал'),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='trainings.training', verbose_name='Тренировка'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingapplication',
            unique_together={('training', 'student')},
        ),
    ]
