# Generated by Django 5.2.4 on 2025-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Заработано баллов')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отметки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-date', '-marked_at'],
            },
        ),
    ]
