# Generated by Django 5.2.4 on 2025-08-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Отметил'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training', verbose_name='Тренировка'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('training', 'student', 'date')},
        ),
    ]
